<template>
  <q-page>
    <div id="stories"></div>
  </q-page>
</template>
<script setup>
  import Zuck from 'zuck.js'
  import 'zuck.js/dist/zuck.css'
  import 'zuck.js/dist/skins/snapgram.css'

  import {onMounted} from 'vue'

  function CreateStory(){
    var timeIndex = 0 ;
    var shifts = [35, 60, 60*3, 60*60*2, 60*60*25, 60*60*24*4, 60*60*24*10]
    var YouTimeAgo  = function(){
      var now = new Date()
      var shift = shifts[timeIndex++] || 0;
      var date = new Date(now - shift*1000);
      return date.getTime() / 1000;
    }
    var mystory = new Zuck("stories",{
      backNative:true,
      previousTap:true,
      autoFullScreen:"autoFullScreen",
      skin:"snapgram",// YOu Custem CLASS
      avatars:true,
      list:true,
      cubeEffect:"cubeEffect",
      localStorage:true,
      stories`:[
      {
        id:"ramon",//YOU ID STORY
        photo:"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/users/1.jpg",
          name: "ramon",             // story name (or user name)
          link: "https://facebook.com", // story link (useless on story generated by script)
         lastUpdated: YouTimeAgo(),
          items:[
          Zuck.buildItem("ramon-1","photo",3,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/1.jpg","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/1.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          Zuck.buildItem("ramon-2","video",0,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/2.mp4","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/2.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          Zuck.buildItem("ramon-3","photo",3,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/3.jpg","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/3.jpg","link to image",
            "You Caption in stories",false,YouTimeAgo()
            )
          ]
      },
      {
        id:"Youname2",//YOU ID STORY
        photo:"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/users/2.jpg",
          name: "Youname2",             // story name (or user name)
          link: "https://facebook.com", // story link (useless on story generated by script)
         lastUpdated: YouTimeAgo(),
          items:[
          Zuck.buildItem("Youname2-1","video",0,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/4.mp4","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/4.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          Zuck.buildItem("Youname2-2","photo",3,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/5.jpg","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/5.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          
          ]
      },
       {
        id:"Youname3",//YOU ID STORY
        photo:"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/users/3.jpg",
          name: "Youname3",             // story name (or user name)
          link: "https://facebook.com", // story link (useless on story generated by script)
         lastUpdated: YouTimeAgo(),
          items:[
          Zuck.buildItem("Youname3-1","photo",3,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/6.jpg","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/6.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          Zuck.buildItem("Youname3-2","photo",3,"https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/7.jpg","https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/7.jpg","link to image",
            false,false,YouTimeAgo()
            ),
          
          ]
      },
        ]
    })

  }

onMounted(()=>{
  CreateStory()
})

</script>
